### PR TITLE
Desktop

### PR DESCRIPTION
**Pull request by FidaaHersh**
Done with desktop style for all pages :tada: :smiley: :muscle:

### CODE REVIEW

**Review by jema28 — CHANGES_REQUESTED** [review]
There are quite a few issues:

1. Home page is in a row.
2. Upload photo is too close to the bottom of the page.
3. Item information and please verify needs to be aligned correctly.
4. The back and login balance looks wrong. It needs to be centered.
5. Your items page header 
6. Three dots have to be centered.

Screenshot 2019-04-14 at 11 45 32
Screenshot 2019-04-14 at 11 45 44
Screenshot 2019-04-14 at 11 46 13
Screenshot 2019-04-14 at 11 46 28
Screenshot 2019-04-14 at 11 46 39
Screenshot 2019-04-14 at 11 49 04

**Comment by jema28** [comment]
You also have to keep merging the new master into your branch.

**Comment by FidaaHersh** [comment]
Frustration :crying_cat_face:

**Review by jema28 — COMMENTED** [review]
The css could be improved here, using percentages in multiples of 5. There are also a lot of indentation problems.

**Pull request merged**
